name: Windows VDS Oluştur ve Test Et

on:
  workflow_dispatch:
    inputs:
      vds_boyutu:
        description: 'VDS Boyutu (örn: t2.medium)'
        required: true
        default: 't2.medium'

jobs:
  create-vds:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Rastgele Şifre Oluştur
        id: pwgen
        run: echo "password=Pass$(openssl rand -hex 6)" >> $GITHUB_OUTPUT

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: VDS Oluştur ve Yapılandır
        run: pwsh ./scripts/create-vds.ps1 -InstanceType "${{ github.event.inputs.vds_boyutu }}" -Password "${{ steps.pwgen.outputs.password }}"
